-- 0007_golfwing_schema: GolfOrder発注管理のPostgres移行スキーマ（DECISIONS #19/#20）
-- D1 (golfwing-production) → schema golfwing。tenants/usersは廃止しcompanies/stores/staffに統合

create schema if not exists golfwing;

-- ===== 仕入先 =====
create table golfwing.suppliers (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  store_id uuid references public.stores(id),
  name text not null,
  alias_names text,
  contact_name text,
  honorific text,
  order_method text,               -- email / fax / line / phone
  phone text,
  email text,
  cc_emails text,                  -- カンマ区切り
  payment_method text,
  notes text,
  shipping_rule text,
  free_shipping_threshold integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 仕入先判定ルール =====
create table golfwing.supplier_rules (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  item_category text,
  manufacturer text,
  club_type text,
  supplier_id bigint not null references golfwing.suppliers(id),
  rate numeric(6,3),
  priority integer not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 商品マスタ =====
create table golfwing.products (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  product_code text,
  barcode text,
  item_category text not null,
  manufacturer text,
  name text not null,
  spec text,
  color text,
  club_type text,
  list_price numeric(12,2),
  default_rate numeric(6,3),
  default_supplier_id bigint references golfwing.suppliers(id),
  unit text not null default '本',
  source text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 商品×仕入先（多対多・仕入先別掛け率） =====
create table golfwing.product_suppliers (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  product_id bigint not null references golfwing.products(id),
  supplier_id bigint not null references golfwing.suppliers(id),
  rate numeric(6,3),
  is_default boolean not null default false,
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 発注 =====
create table golfwing.purchase_orders (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  store_id uuid references public.stores(id),
  batch_code text not null,
  order_no text not null unique,
  order_date date not null,
  ordered_by text,                 -- 移行時は氏名テキスト。将来staff_id化
  staff_id uuid references public.staff(id),
  supplier_id bigint not null references golfwing.suppliers(id),
  customer_name text,
  usage_type text,
  requested_delivery_date date,
  status text not null default 'draft',  -- draft/pool/ordered/partial/completed 等（D1準拠のtext運用）
  order_note text,
  email_subject text,
  email_body text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 発注明細 =====
create table golfwing.purchase_order_items (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  purchase_order_id bigint not null references golfwing.purchase_orders(id),
  product_id bigint references golfwing.products(id),
  item_category text not null,
  manufacturer text,
  product_name text not null,
  spec text,
  color text,
  club_type text,
  quantity integer not null default 1,
  list_price numeric(12,2),
  rate numeric(6,3),
  unit_price numeric(12,2),
  amount numeric(12,2),
  customer_name text,
  usage_type text,
  requested_delivery_date date,
  line_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 入荷 =====
create table golfwing.receipts (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  purchase_order_id bigint not null references golfwing.purchase_orders(id),
  received_date date not null,
  slip_date date,
  inspected_by text,
  slip_verified boolean not null default false,
  no_slip boolean not null default false,
  slip_checked_by text,
  slip_checked_at timestamptz,
  slip_note text,
  actual_supplier_id bigint references golfwing.suppliers(id),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== 入荷明細 =====
create table golfwing.receipt_items (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  receipt_id bigint not null references golfwing.receipts(id),
  purchase_order_item_id bigint not null references golfwing.purchase_order_items(id),
  received_quantity integer not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== インデックス =====
create index idx_gw_suppliers_company on golfwing.suppliers(company_id);
create index idx_gw_rules_supplier on golfwing.supplier_rules(supplier_id);
create index idx_gw_rules_company on golfwing.supplier_rules(company_id);
create index idx_gw_products_company on golfwing.products(company_id);
create index idx_gw_products_category on golfwing.products(item_category);
create index idx_gw_products_manufacturer on golfwing.products(manufacturer);
create index idx_gw_ps_product on golfwing.product_suppliers(product_id);
create index idx_gw_ps_supplier on golfwing.product_suppliers(supplier_id);
create index idx_gw_po_company on golfwing.purchase_orders(company_id);
create index idx_gw_po_supplier on golfwing.purchase_orders(supplier_id);
create index idx_gw_po_batch on golfwing.purchase_orders(batch_code);
create index idx_gw_po_status on golfwing.purchase_orders(status);
create index idx_gw_poi_order on golfwing.purchase_order_items(purchase_order_id);
create index idx_gw_receipts_order on golfwing.receipts(purchase_order_id);
create index idx_gw_ri_receipt on golfwing.receipt_items(receipt_id);

-- ===== updated_at trigger =====
do $$
declare t text;
begin
  foreach t in array array['suppliers','supplier_rules','products','product_suppliers','purchase_orders','purchase_order_items','receipts','receipt_items']
  loop
    execute format('create trigger set_updated_at before update on golfwing.%I for each row execute function app.set_updated_at()', t);
  end loop;
end $$;

-- ===== RLS（テナント分離。管理系書き込みはservice_role経由: DECISIONS #11踏襲） =====
do $$
declare t text;
begin
  foreach t in array array['suppliers','supplier_rules','products','product_suppliers','purchase_orders','purchase_order_items','receipts','receipt_items']
  loop
    execute format('alter table golfwing.%I enable row level security', t);
    execute format('create policy tenant_select on golfwing.%I for select to authenticated using (company_id = app.current_company_id())', t);
    execute format('create policy tenant_insert on golfwing.%I for insert to authenticated with check (company_id = app.current_company_id())', t);
    execute format('create policy tenant_update on golfwing.%I for update to authenticated using (company_id = app.current_company_id())', t);
  end loop;
end $$;

-- ===== 権限 =====
grant usage on schema golfwing to authenticated, service_role;
grant select, insert, update, delete on all tables in schema golfwing to authenticated, service_role;
grant usage, select on all sequences in schema golfwing to authenticated, service_role;
alter default privileges in schema golfwing grant select, insert, update, delete on tables to authenticated, service_role;
alter default privileges in schema golfwing grant usage, select on sequences to authenticated, service_role;

-- ===== Genesis KPI用ビュー: 月次仕入コスト =====
create view golfwing.v_monthly_purchase_cost as
select
  po.company_id,
  po.store_id,
  date_trunc('month', po.order_date)::date as month,
  s.name as supplier_name,
  count(distinct po.id) as order_count,
  sum(poi.amount) as total_amount
from golfwing.purchase_orders po
join golfwing.purchase_order_items poi on poi.purchase_order_id = po.id
join golfwing.suppliers s on s.id = po.supplier_id
where po.status <> 'draft'
group by po.company_id, po.store_id, date_trunc('month', po.order_date), s.name;

grant select on golfwing.v_monthly_purchase_cost to authenticated, service_role;
